#!/bin/bash
TEMPERATURE=$(nvidia-smi stats -d temp -c 1 | cut -b 32,33)
LOGO=""
#echo $TEMPERATURE
if ((TEMPERATURE < 40))
then
LOGO=""

elif ((TEMPERATURE < 60))
then
LOGO=""

elif ((TEMPERATURE < 70))
then
LOGO=""

elif ((TEMPERATURE < 80))
then
LOGO=""

else
LOGO=""

fi

echo $LOGO