#! /bin/sh
setxkbmap -layout fr
sxhkd &
setxkbmap -layout fr &
picom &
nitrogen --restore &
xsetroot -cursor_name left_ptr &
#polybar example &
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V

bspc config border_width         2
bspc config window_gap          7

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -r "*"
bspc rule -a eww --layer below

playerctld

setxkbmap -layout fr
eww daemon
eww open-many leftbar rightbar folder-revealer profile neofetch musicplayer

setxkbmap -layout fr
